function loadSounds ()
	startSound = love.audio.newSource("game/sound/start.wav", "static")
    deathSound = love.audio.newSource("game/sound/death.wav", "static")
    playerHitSound = love.audio.newSource("game/sound/phit.wav", "static")
    enemyHitSound = love.audio.newSource("game/sound/ehit.wav", "static")
    playerLaserSound = love.audio.newSource("game/sound/plaser.wav", "static")
    enemyLaserSound = love.audio.newSource("game/sound/elaser.wav", "static")
    music = love.audio.newSource("game/sound/music.mp3", "stream")

    playerHitSound:setVolume(0.2)
    enemyHitSound:setVolume(0.2)
    playerLaserSound:setVolume(0.2)
    enemyLaserSound:setVolume(0.2)
    music:setVolume(0.2)
end